name: licem
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pytorch:pytorch>=2.1
  - torchvision>=0.17.1
  - pytorch:pytorch-cuda
  - hydra-core=1.3.*
  - scipy
  - scikit-learn
  - lightning
  - matplotlib
  - opencv
  - pip
  - pip:
    - wandb
    - sentence-transformers
    - SciencePlots
    - hydra-core
    - plotly
    - scikit-learn-extra
    - numpy==1.26.4
    - pandas
    - git+https://github.com/pyc-team/pytorch_concepts.git@models
    - transformers
    - datasets
    - openai
    - mistralai
    - xgboost