defaults:
  - common
  - _self_

loader: 
  name: awa2_incomplete
  batch_size: 128
  selected_concepts: [black, gray, stripes, hairless, flippers, paws, plains, fierce, solitary]

# Dataset parameters
metadata:
  task: classification
  lr: 0.0001
  name: awa2_incomplete

latent_size: 128

# We generated the Awa2 incomplete dataset following the same procedure as in the paper: https://arxiv.org/pdf/2504.17921v1.
# More precisely, selecting the following concepts:
# “black”, “gray”, “stripes”, “hairless”, “flippers”, “paws”, “plains”, “fierce”, “solitary” 