defaults:
  - common
  - _self_

loader:
  dataset: banking
  selected_concepts: [Transaction_Mention, Issue/Problem_Description, Account_Reference, Request_for_Help_or_Clarification]
  concept_annotations: false
  
metadata:
  lr: 0.001
  name: banking
  finetune_backbone: false
  examples: "Query: how do i locate my card?\nAnswer: 11\n\nQuery: can i use google pay with this account?\nAnswer: 2"