defaults:
  - common
  - _self_

loader:
  name: celeba
  batch_size: 128  
  # We select the 8 attributes whose distribution is closer to a random uniform binary distribution
  class_attributes: ["Young","Attractive","Mouth_Slightly_Open","Smiling","Wearing_Lipstick","High_Cheekbones","Male","Heavy_Makeup"]

# Dataset parameters
metadata:
  task: classification
  lr: 0.0005
  name: celeba

latent_size: 128

# List of attributes of the CelebA dataset and their balance

#ID:           Attribute:  Balance:
#24             No_Beard  0.834940
#39                Young  0.773617
#2            Attractive  0.512505
#21  Mouth_Slightly_Open  0.483428
#31              Smiling  0.482080
#36     Wearing_Lipstick  0.472436
#19      High_Cheekbones  0.455032
#20                 Male  0.416754
#18         Heavy_Makeup  0.386922
#33            Wavy_Hair  0.319567
#25            Oval_Face  0.284143
#27          Pointy_Nose  0.277445
#1       Arched_Eyebrows  0.266981
#6              Big_Lips  0.240796
#8            Black_Hair  0.239251
#7              Big_Nose  0.234532
#32        Straight_Hair  0.208402
#11           Brown_Hair  0.205194
#3       Bags_Under_Eyes  0.204572
#34     Wearing_Earrings  0.188925
#5                 Bangs  0.151575
#9            Blond_Hair  0.147992
#12       Bushy_Eyebrows  0.142168
#37     Wearing_Necklace  0.122967
#23          Narrow_Eyes  0.115149
#0      5_o_Clock_Shadow  0.111136
#28    Receding_Hairline  0.079778
#38      Wearing_Necktie  0.072715
#29          Rosy_Cheeks  0.065721
#15           Eyeglasses  0.065119
#16               Goatee  0.062764
#13               Chubby  0.057567
#30            Sideburns  0.056511
#10               Blurry  0.050899
#35          Wearing_Hat  0.048460
#14          Double_Chin  0.046688
#26            Pale_Skin  0.042947
#17            Gray_Hair  0.041950
#22             Mustache  0.041545
#4                  Bald  0.022443
