defaults:
  - common
  - _self_

loader:
  dataset: clinc
  selected_concepts: [Domain_Mention, Intent_Specific_Keywords, Action_Request, Out-of-Scope_Indicators]
  concept_annotations: false
  
metadata:
  lr: 0.001
  name: clinc
  finetune_backbone: false
  examples: "Query: what's the exchange rate for euros today\nAnswer: 38\n\nQuery: i'd like to update my shopping list\nAnswer: 125"