loader:
  _target_: src.loaders.dataloader.TextDataLoader
  model_name: ${lm_name}  
  batch_size: ${batch_size}  
  llm_client:
    _target_: src.loaders.llm_client.llm_client
    LLM: ${llm_name}
    temperature: 0.7
    max_tries: 1

latent_size: ${latent_size}