defaults:
  - dataset: cebab
  - model: blackbox
  - engine: engine

## Common parameters
max_epochs: 500
patience: 40
gamma: 0.5
lr_patience: 20
gpus: [0]
seed: 1
activation: LeakyReLU
num_workers: 0

## These parameters can be overridden by the dataset config
latent_size: 64
batch_size: 256

## Shared Concept-based model parameters
task_penalty: 0.1
int_prob: 0.25

## Shared Concept-embedding based model
embedding_size: 16

## Default supervision strategy
supervision: supervised

## Name of the LLM used to generate the concepts
llm_name: 'gpt-4o' #, mistral-7b-instruct-v0.1, mistral-7b-instruct-v0.2

## Whether to use the embeddings of a pre-trained language model
use_embeddings: True

## Parameters for the encoder
# those parameters are needed if the "use_embedding" is set to False
encoder_name: bert-base-uncased
fine_tune_encoder: True
encoder_output_size: 768 # This is the output size of the encoder, e.g., 768 for BERT, 1024 for RoBERTa

## Pre-trained Language model name
lm_name: all-distilroberta-v1
lm_embedding_size: 768

# Set this parameter to True if you want to use the stored, preprocessed dataset,
# otherwise it will be preprocessed from scratch and saved in the cache. 
use_stored_dataset: False

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      seed: 1 #, 2, 3
      # implemented image datasets: mnist_addition, cub, celeba, awa2
      # implemented textual datasets: ...
      dataset: cebab
      # implemented models: blackbox, cbm_linear, cbm_mlp, cbm_dt, cbm_xg, cem, dcr, licem
      model: blackbox #, cbm_linear, cem, licem, dcr, cmr
      # possible supervision strategies: supervised, unsupervised, self_supervised
      # supervision: supervised, unsupervised, self_supervised

wandb:
  # Set the params below if you want to use wandb as logger.
  # Set it to null if you do not want to use wandb.
  project: "licem" # Set to your project name
  entity: "francescothesantis-politecnico-di-torino" # Set to your wandb entity name

# The note will be appended to the group name in wandb 
# and will be considered as an additional tag (for filtering).
# If you do not want to add any note, set it to null.
note: null