
params:
  _target_: "src.models.blackbox.BlackBox"
  activation: ${activation}
  latent_size: ${dataset.latent_size}

  # These values can be overridden by the dataset configuration
  encoder:
    _target_: src.models.encoders.LinearEncoder
    input_size: ${input_size}
    output_size: ${dataset.latent_size}
    input_transform: null

metadata:
  name: blackbox
