defaults:
  - common
  - _self_
  
params:
  _target_: "src.models.cbm.ConceptBottleneckModel"
  task_penalty: ${task_penalty}
  classifier: mlp
  int_prob: ${int_prob}
  weight_reg: ${weight_reg}

metadata:
  name: cbm_mlp