defaults:
  - common
  - _self_
  
params:
  _target_: "src.models.cbm.ConceptBottleneckModel"
  task_penalty: ${task_penalty}
  task_interpretable: false
  int_prob: ${int_prob}

metadata:
  name: cbm_mlp