defaults:
  - common
  - _self_
  
params:
  _target_: "src.models.cmr.ConceptMemoryReasoner"
  task_penalty: ${task_penalty}
  int_prob: ${int_prob}
  memory_size: ${memory_size}
  conc_rec_weight: 0.1
  embedding_size: ${embedding_size}


metadata:
  name: cmr