params:
  activation: ${activation}
  latent_size: ${dataset.latent_size}
  hard_concepts: ${dataset.hard_concepts}

  # The decoder can be overridden by the dataset configuration
  encoder:
    _target_: src.models.encoders.LinearEncoder
    input_size: ${input_size}
    output_size: ${dataset.latent_size}
    activation: ${activation}