params:
  activation: ${activation}
  latent_size: ${dataset.latent_size}
  use_embeddings: ${use_embeddings}

  # Encoder parameters
  encoder:
    _target_: src.models.encoders.base_encoder.BaseEncoder
    model_name: ${encoder_name}
    fine_tune: ${fine_tune_encoder}
  encoder_output_size: ${encoder_output_size}
  lm_embedding_size: ${lm_embedding_size}
