defaults:
  - common
  - _self_
  
params:
  _target_: "src.models.dcr.DeepConceptReasoner"
  task_penalty: ${task_penalty}
  int_prob: ${int_prob}
  temperature: 100
  embedding_size: ${embedding_size}

metadata:
  name: dcr