defaults:
  - common
  - _self_
  
params:
  _target_: "src.models.licem.LinearConceptEmbeddingModel"
  task_penalty: ${task_penalty}
  int_prob: ${int_prob}
  embedding_size: ${embedding_size}
  use_bias: true
  weight_reg: ${weight_reg}
  bias_reg: 1e-6

metadata:
  name: licem