defaults:
  - common
  - _self_
  
params:
  _target_: "src.models.m_licem.LinearMemoryReasoner"
  task_penalty: ${task_penalty}
  int_prob: ${int_prob}
  memory_size: ${memory_size}
  negative_concepts: False
  weight_reg: 1e-4
  embedding_size: ${embedding_size}
  embedding_memory: True
  intervene_on_selection: False
  linear_classifier_selection: False

metadata:
  name: m_licem_sampling